name: gha_example:GitHub Action exercise

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    # Definicja systemu do instalacji na weźle roboczym
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.0
          buildkitd-flags: --debug

      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # Logowanie do Dockerhub-a
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Budowa obrazu dla dwóch architektur sprzętowych
      # oraz przesłanie do własnego repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64/v8,linux/amd64
          context: .
          file: ./Dockerfile_prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gha_lab10:zadv1
          cache-from: type=registry,ref=gha_lab10:zadv1
          cache-to: type=registry,ref=gha_lab10:zadv1,mode=max
        # tags: |
        #   ${{ secrets.DOCKERHUB_USERNAME }}/gha_lab10:zadv1
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
